services:
  transactions-web-api:
    image: ${DOCKER_REGISTRY-}transactionswebapi
    container_name: products.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
      - "5011:5011"
    depends_on:
      - "transactions-database"

  transactions-database:
    image: postgres:latest
    container_name: transactions-database
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - 5432:5432